### ISSUE TITLE
"Borrowed value does not live long enough" compilation error

### ISSUE THREAD

**Issue by matt-williams** [abonander/multipart-async#3]
Trying to compile the latest code (https://github.com/abonander/multipart-async/tree/2dd43a5c619bc5fd729d2a974ebcf610dc59074b), I get the following error:

```
   Compiling multipart-async v0.0.2 (file:///data/mirw/multipart-async)
error[E0597]: borrowed value does not live long enough
   --> src/server/field/headers.rs:285:57
    |
285 |     let mut tk_splits = input.splitn(2, &['"', ';'][..]);
    |                                          ----------     ^ temporary value dropped here while still borrowed
    |                                          |
    |                                          temporary value created here
...
303 | }
    | - temporary value needs to live until here
    |
    = note: consider using a `let` binding to increase its lifetime

error: aborting due to previous error

error: Could not compile `multipart-async`.

To learn more, run the command again with --verbose.
```

I fixed it locally by making the `['"', ';']` array into a static constant...

```
diff --git a/src/server/field/headers.rs b/src/server/field/headers.rs
index da41fad..e038923 100644
--- a/src/server/field/headers.rs
+++ b/src/server/field/headers.rs
@@ -282,7 +282,8 @@ fn param_name(input: &str) -> Option<(&str, &str)> {

 fn param_val(input: &str) -> Option<(&str, &str)> {
     // continue until the opening quote or the terminating semicolon
-    let mut tk_splits = input.splitn(2, &['"', ';'][..]);
+    static QUOTE_SEMICOLON: [char; 2] = ['"', ';'];
+    let mut tk_splits = input.splitn(2, &QUOTE_SEMICOLON[..]);

     let token = try_opt!(tk_splits.next()).trim();
     let rem = tk_splits.next().unwrap_or("");
```

...but I'm not sure whether this is the best fix?  What do you think?

Looking forward to multipart support for the new async hyper - thanks for all your efforts!

**Comment by abonander** [comment]
Sorry, for some reason I didn't get any notifications for new issues on this repo.

@matt-williams @mirw This crate is still in its development phase and I'm not really intending anyone to use it yet. This doesn't compile for you because it's using [rvalue static promotion stabilized in 1.20](https://github.com/rust-lang/rust/blob/master/RELEASES.md#language-1), though that wasn't released yet when this issue was opened. Do you need support for 1.19 and earlier? Because I'd like to make use of newer APIs were I can, this being a whole new crate and all.

**Comment by matt-williams** [comment]
Thanks!  No need for rust 1.19 support - as you say, that was just the latest stable when I tried the code.

I was looking at this as part of porting the `rust-server` code generator for Swagger APIs (https://github.com/swagger-api/swagger-codegen) to run on async Hyper.  For now, I've just left handling of multipart bodies using the standard multipart library - this means that we have to receive the whole of the body before parsing it, rather than being able to stream, but other than that it works.

Happy to close this!

**Comment by abonander** [comment]
The core API is mostly there, it's more of a "use at your own risk" kind of thing since there's still changes to do. I haven't updated it to Futures 0.2 yet and I'm not sure if I want to mess with Tokio-level integration since this technically falls under Tokio's purview of a "pipelined streaming protocol" though there's no decoding necessary for responses. I'm probably going to keep the same kind of higher-level integration as the original `multipart` library.
